
name: urban_analytics_2021
channels:
  - defaults
  - conda-forge
  - ostrokach-forge
  - pkgw-forge
dependencies:
  - python=3.6
  - pygobject
  - matplotlib
  - scikit-learn
  - numpy
  - pandas
  - networkx
  - pip:
    - powerlaw
    - python-louvain
